const ERROR_CODES = {

    // auth
    INVALID_CREDENTIALS:
        "INVALID_CREDENTIALS",

    TOKEN_EXPIRED:
        "TOKEN_EXPIRED",

    UNAUTHORIZED:
        "UNAUTHORIZED",

    FORBIDDEN:
        "FORBIDDEN",

    // user
    USER_NOT_FOUND:
        "USER_NOT_FOUND",

    // not found
    NOT_FOUND: "NOT_FOUND",

    // bad request
    BAD_REQUEST: "BAD_REQUEST",

    // rate limit
    TOO_MANY_REQUESTS:
        "TOO_MANY_REQUESTS",

    // exist
    EXIST: "ID_EXIST_IN_OTHER_TABLE",

    EMAIL_ALREADY_EXISTS:
        "EMAIL_ALREADY_EXISTS",

    USER_ALREADY_EXISTS:
        "USER_ALREADY_EXISTS",

    // validation
    VALIDATION_ERROR:
        "VALIDATION_ERROR",

    // server
    INTERNAL_SERVER_ERROR:
        "INTERNAL_SERVER_ERROR",

    ACCESS_DENIED:
        "ACCESS_DENIED",

    // quiz
    QUIZ_IS_DRAFT:
        "QUIZ_IS_DRAFT",

    QUIZ_NOT_FOUND:
        "QUIZ_NOT_FOUND",

    // assignment
    ASSIGNMENT_NOT_FOUND:
        "ASSIGNMENT_NOT_FOUND",

    ASSIGNMENT_DRAFT:
        "ASSIGNMENT_DRAFT",

    ASSIGNMENT_NOT_PUBLISHED:
        "ASSIGNMENT_NOT_PUBLISHED",

    ASSIGNMENT_EXPIRED:
        "ASSIGNMENT_EXPIRED",

    ASSIGNMENT_NOT_STARTED:
        "ASSIGNMENT_NOT_STARTED",

    // attempt
    ATTEMPT_NOT_FOUND:
        "ATTEMPT_NOT_FOUND",

    ATTEMPT_ALREADY_SUBMITTED:
        "ATTEMPT_ALREADY_SUBMITTED",

    ATTEMPT_TIMEOUT:
        "ATTEMPT_TIMEOUT",

    ATTEMPT_IN_PROGRESS:
        "ATTEMPT_IN_PROGRESS",

    // student
    STUDENT_NOT_FOUND:
        "STUDENT_NOT_FOUND",

    // guest
    GUEST_NAME_REQUIRED:
        "GUEST_NAME_REQUIRED",

    // access
    ACCESS_DENIED:
        "ACCESS_DENIED",

    // quiz already assigned
    QUIZ_ALREADY_ASSIGNED:
        "QUIZ_ALREADY_ASSIGNED",
};

module.exports = ERROR_CODES;
